### ISSUE TITLE
Info about magnet sensor and motion sensor

### ISSUE THREAD

**Issue by garvarma** [fooxy/homeassistant-aqara#3]
Hello,

First of all i want to say thanks for this developemtn about xioami smart home and their sensor.

Now i write to you because i have some doubts about magnet and motions sensors in home assistant.

How do you define them like binary.sensor or like sensor? I ask this, because i want integrate in homekit by home assistant homebridge, but in website, talks about binary sensor and in your example in github, you explain to define the xiaomi system like a sensor, but in automation talk about binary sensor.

Other thing using your custome component, is possible to link alarm HA with xioami alarm gateway? 

thanks

**Comment by fooxy** [comment]
Hello @garvarma,

Actually I'm currently restructuring all the code in order to:
- get data for temperature and humidity polling the gateway
- push data to home-asssitant for motion, magnet and switch.

Each sensor is define like this:
 - H&T sensor : sensor
 - Magnet : binary sensor
 - Motion : binary sensor
 - Switch button : switch

It takes more time than I expected but I hope to have something working soon.

For the alarm HA I don't know if it is possible, but I will have a look :)
